location:
  source_directories:
    - /etc
    - /home
    - /root
    - /var
  repositories:
    - /mnt/data1/backup
  exclude_patterns:
    - '/home/*/.cache/*'
    - '/home/*/.stack/*'
    - '/var/cache/*'
    - '/var/tmp/*'
    - '/var/lib/docker/*'
    - '*.pyc'
  exclude_caches: true

storage:
  compression: lz4

retention:
  keep_hourly: 24
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
