# syntax {{{
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add='''
  let g:cpp_class_scope_highlight = 1
  let g:cpp_member_variable_highlight = 1
  let g:cpp_class_decl_highlight = 1
  let g:cpp_experimental_simple_template_highlight = 1
  let g:cpp_concepts_highlight = 1
  let g:cpp_no_function_highlight = 1

  let g:vim_json_syntax_conceal = 0

  autocmd vimrc BufRead,BufNewFile *.vue setlocal filetype=vue.html.javascript.css
'''

[[plugins]]
repo = 'anntzer/vim-cython'

[[plugins]]
repo = 'vhda/verilog_systemverilog.vim'
# }}}

# java {{{
[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
hook_add = '''
  let g:JavaComplete_UsePython3 = 1
  autocmd vimrc FileType java setlocal omnifunc=javacomplete#Complete
'''
# }}}

# latex {{{
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['bib', 'tex']
hook_add='''
  let g:vimtex_compiler_latexmk = {
    \ 'continuous' : 1,
    \ 'options' : [
    \   '-pdfdvi',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}

  if executable('qpdfview')
    let g:vimtex_view_general_viewer = 'qpdfview'
    let g:vimtex_view_general_options = '--unique @pdf\#src:@tex:@line:@col'
    let g:vimtex_view_general_options_latexmk = '--unique'
  endif

  if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
  endif
  autocmd vimrc FileType tex let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme
'''

# }}}

# doc {{{
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
type__depth = 1
hook_add = '''
  set helplang=ja,en
'''
# }}}

# appearance {{{
[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
  if !exists('g:context_filetype#filetypes')
    let g:context_filetype#filetypes = {}
  endif
  let g:context_filetype#filetypes.gdb = [{'filetype': 'python', 'start' : '^python$', 'end' : '^end$'}]
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeRespectWildIgnore = 1
  nnoremap <silent> <Leader>n :<C-u>NERDTreeToggle<CR>
  autocmd vimrc BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_fileTypeExclude = ['help', 'tagbar', 'git', '']
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_nr_show = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='simple'
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  autocmd vimrc VimEnter * nested colorscheme hybrid
'''

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'junegunn/rainbow_parentheses.vim'
on_ft = ['cpp']
hook_source = '''
  let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]
  autocmd vimrc VimEnter * RainbowParentheses
'''

[[plugins]]
repo = 'thinca/vim-zenspace'

# }}}

# git {{{
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
# }}}

# editor {{{
[[plugins]]
repo = 'Valloric/YouCompleteMe'
type__depth = 1
build = 'python3 install.py $( which clang >/dev/null && echo "--clang-completer") $( which npm >/dev/null && echo "--js-completer" ) $( which cargo >/dev/null && echo "--rust-completer")'
hook_add = '''
  let g:ycm_python_binary_path = executable('python3') ? 'python3' : 'python'
  let g:ycm_global_ycm_extra_conf = expand('~/.ycm_extra_conf.py')
  let g:ycm_autoclose_preview_window_after_completion = 1
  if executable('rustc')
    let g:ycm_rust_src_path = system('rustc --print sysroot') + '/lib/rustlib/src/rust/src'
  endif
  autocmd vimrc FileType c,cpp,objc,objcpp,cs,go,javascript,python,rust nnoremap <buffer> <CR> :<C-u>YcmCompleter GoTo<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  let g:tagbar_width = 30
  let g:tagbar_show_visibility = 1
  let g:tagbar_type_bib = {
    \ 'ctagstype' : 'bib',
    \ 'kinds'     : [
      \ 'a:Articles',
      \ 'b:Books',
      \ 'L:Booklets',
      \ 'c:Conferences',
      \ 'B:Inbook',
      \ 'C:Incollection',
      \ 'P:Inproceedings',
      \ 'm:Manuals',
      \ 'T:Masterstheses',
      \ 'M:Misc',
      \ 't:Phdtheses',
      \ 'p:Proceedings',
      \ 'r:Techreports',
      \ 'u:Unpublished',
    \ ]
  \ }
  function! s:nop()
  endfunction
  augroup TagbarProjects
    autocmd!
    autocmd User * call s:nop()
    autocmd User dein.toml let b:tagbar_type = {
      \ 'ctagstype' : 'dein',
      \ 'kinds'     : [
        \ 'r:Repo',
      \ ]
    \ }
  augroup END
  nnoremap <silent> <LEADER>t :<C-u>TagbarToggle<CR>
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
  autocmd vimrc BufWritePre * FixWhitespace
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_column_always = 1
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_cpp_clangcheck_options='-extra-arg=-D__clang_analyzer__'
  let g:ale_cpp_cppcheck_options='--enable=all --suppress=unusedFunction --suppress=syntaxError'
  let g:ale_cpp_clangtidy_checks=[]
  let g:ale_rust_cargo_use_clippy = 1
  let g:ale_c_clangformat_options = '-fallback-style=Google -style=file -assume-filename=%s'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_fix_on_save = 1
  let g:ale_linters = { 'cpp': ['clangcheck', 'clangtidy_h', 'cppcheck', 'cpplint', 'clang-format'] }
  let g:ale_fixers = {
  \ 'cpp': ['clang-format'],
  \ 'python': ['isort', 'yapf'],
  \ 'css': ['prettier', 'stylelint'],
  \ 'javascript': ['prettier', 'eslint'],
  \ 'json': ['prettier'],
  \ 'rust': ['rustfmt'],
  \ 'java': ['clang-format'],
  \ 'verilog': [
  \   {buffer, lines -> {'command': 'iStyle --style=ansi -s2 -p -n %t', 'read_temporary_file': 1}}
  \ ]
  \}
  let g:ale_fixers.verilog_systemverilog = g:ale_fixers.verilog
  let g:ale_linter_aliases = {
  \ 'verilog_systemverilog': ['verilog']
  \}
  autocmd vimrc FileType cpp if exists('g:build_dir') | let g:ale_c_build_dir = g:build_dir | endif
  nmap [w <Plug>(ale_previous_wrap)
  nmap ]w <Plug>(ale_next_wrap)
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign'
hook_add = '''
  xmap ga <Plug>(EasyAlign)
  nmap ga <Plug>(EasyAlign)
  let g:easy_align_delimiters = {'t': {'pattern': "\<tab>", 'left_margin': 0, 'right_margin': 0}}
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  autocmd vimrc FileType python nnoremap <buffer> @p :T python3 %<CR><Ctrl-W>j
'''

[[plugins]]
repo = 'embear/vim-localvimrc'
hook_add = '''
  let g:localvimrc_persistent = 1
'''

[[plugins]]
repo = 'tyru/caw.vim'
merged = 0

[[plugins]]
repo = 'junegunn/fzf'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  noremap <Leader>f :<C-u>Files<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'ciaranm/detectindent'
hook_add = '''
  let g:detectindent_preferred_expandtab = 1
  "autocmd vimrc BufReadPost * DetectIndent
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_use_migemo = 1
'''

[[plugins]]
repo = 'lilydjwg/fcitx.vim'
on_if = '$USER !=# "root" && !empty(glob("/tmp/fcitx-socket-*"))'

[[plugins]]
repo = 'vim-scripts/restore_view.vim'
hook_add = '''
  set viewoptions=cursor,folds,slash,unix
'''

[[plugins]]
repo = 'kana/vim-altr'
on_map = '<Plug>'
hook_add = '''
  nmap <Leader>a <Plug>(altr-forward)
  nmap <Leader>A <Plug>(altr-back)
'''
hook_post_source = '''
  call altr#define('%/include/%.hpp', '%/include/*/%.hpp', '%/include/*/*/%.hpp', '%/include/*/*/%.inl.hpp', '%/src/%.hpp', '%/src/%.h', '%/src/%.cpp', '%/test/%Test.cpp', '%/test/%_test.cpp', '%/test/%.cpp')
'''

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
hook_add = '''
  let g:gutentags_ctags_exclude = ['build/*']
'''

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsExpandTrigger = '<C-S>'
  let g:UltiSnipsJumpForwardTrigger = ']s'
  let g:UltiSnipsJumpBackwardTrigger = '[s'
'''

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'tpope/vim-speeddating'
on_map = ['<C-A>', '<C-X>']

[[plugins]]
repo = 'tpope/vim-repeat'
on_map = '.'

[[plugins]]
repo = 'johnsyweb/vim-makeshift'

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = ['c', 'cpp', 'python']

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']
hook_add = '''
  let g:gundo_close_on_revert = 1
  let g:gundo_auto_preview = 0
  let g:gundo_prefer_python3 = 1
  nnoremap <Leader>u :<C-u>GundoToggle<CR>
'''

[[plugins]]
repo = 'romainl/vim-qf'
# }}}
