#!/bin/bash

# set environmental variables before running commands
# LUKS_PASSWD=
# DEVICE=/dev/sda
# DEVICE_BOOT=/dev/sda1
# DEVICE_DATA=/dev/sda2

install_init() {
  loadkeys jp106
  setfont latarcyrheb-sun32
  timedatectl set-ntp true
  curl -sSL "https://www.archlinux.org/mirrorlist/?country=JP&protocol=http&protocol=https&ip_version=4&ip_version=6" >/etc/pacman.d/mirrorlist
  sed -i "s/^#Server/Server/" /etc/pacman.d/mirrorlist
}

install_checkmode() {
  if [[ -d /sys/firmware/efi/efivars ]]; then
    echo "EFI"
  else
    echo "BIOS"
  fi
}

install_partition() {
  set -euo pipefail
  sgdisk -Z -n "0::+512M" -t 0:ef00 -n "0::" -t 0:8300 -p "$DEVICE"
  mkfs.fat -F32 "$DEVICE_BOOT"
  if [[ -n $LUKS_PASSWD ]]; then
    echo -n "$LUKS_PASSWD" | cryptsetup luksFormat "$DEVICE_DATA" -q -d -
    echo -n "$LUKS_PASSWD" | cryptsetup open "$DEVICE_DATA" cryptroot -d -
    mkfs.ext4 /dev/mapper/cryptroot
    cryptsetup close cryptroot
  else
    mkfs.ext4 "$DEVICE_DATA"
  fi
}

install_mount() {
  set -euo pipefail
  if [[ -n $LUKS_PASSWD ]]; then
    echo -n "$LUKS_PASSWD" | cryptsetup open "$DEVICE_DATA" cryptroot -d -
    mount /dev/mapper/cryptroot /mnt
  else
    mount "$DEVICE_DATA" /mnt
  fi
  mkdir -p /mnt/boot
  mount "$DEVICE_BOOT" /mnt/boot
}

install_system() {
  pacstrap /mnt base base-devel linux linux-lts linux-firmware dhcpcd
  cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
}

install_setup() {
  genfstab -U /mnt >> /mnt/etc/fstab
  arch-chroot /mnt ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  arch-chroot /mnt hwclock --systohc --utc
  echo KEYMAP=jp106 > /mnt/etc/vconsole.conf
  sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/; s/^# Defaults env_keep += "HOME"/ Defaults env_keep += "HOME"/' /mnt/etc/sudoers
}

install_hostname() {
  if [[ -z $1 ]]; then
    echo "usage: install_hostname HOSTNAME"
    return 1
  fi

  echo "$1" > /mnt/etc/hostname
  cat << EOS > /mnt/etc/hosts
127.0.0.1	localhost
::1		localhost
127.0.1.1	$1.localdomain	$1
EOS
}

install_bootloader() {
  set -euo pipefail
  sed -i "s/^HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)$/HOOKS=(base udev autodetect modconf keyboard keymap block encrypt filesystems keyboard fsck)/" /mnt/etc/mkinitcpio.conf
  arch-chroot /mnt mkinitcpio -P
  arch-chroot /mnt bootctl --path=/boot install
  if lscpu | grep GenuineIntel >/dev/null; then
    local -r UCODE="initrd  /intel-ucode.img"
    pacstrap /mnt intel-ucode
  elif lscpu | grep AuthenticAMD >/dev/null; then
    local -r UCODE="initrd  /amd-ucode.img"
    pacstrap /mnt amd-ucode
  else
    local -r UCODE=
  fi
  local -r PARTUUID="$(blkid -s PARTUUID -o value "$DEVICE_DATA")"
  if [[ -n $LUKS_PASSWD ]]; then
    local -r OPTS="root=/dev/mapper/cryptroot cryptdevice=PARTUUID=${PARTUUID}:cryptroot:allow-discards add_efi_memmap"
  else
    local -r OPTS="root=PARTUUID=${PARTUUID} add_efi_memmap"
  fi
  cat <<EOS >/mnt/boot/loader/entries/arch.conf
title   Arch Linux
linux   /vmlinuz-linux
$UCODE
initrd  /initramfs-linux.img
options $OPTS
EOS
  cat <<EOS >/mnt/boot/loader/entries/arch-lts.conf
title   Arch Linux (LTS)
linux   /vmlinuz-linux-lts
initrd  /initramfs-linux-lts.img
options $OPTS
EOS
  cat <<EOS >/mnt/boot/loader/loader.conf
default Arch Linux
timeout 3
editor  yes
EOS
}

install_user() {
  if [[ -z $1 ]]; then
    echo "usage: install_user USER"
    return 1
  fi

  pacstrap /mnt git zsh
  arch-chroot /mnt useradd -m -g wheel -s /bin/zsh "$1"
  arch-chroot /mnt passwd "$1"
  arch-chroot /mnt su "$1" -c "git clone https://github.com/regen100/dotfiles.git ~/dotfiles"
}
